{{- if .Values.backup.enabled -}}
apiVersion: policy/v1
kind: backup
metadata:
  name: {{ .Values.backup.backupName | default (include "base.fullname" .) }}
spec:
  minAvailable: {{ .Values.backup.minAvailable }}
  selector:
    matchLabels:
      {{- include "base.selectorLabels" . | nindent 6 }}
    backend:
     {{- include ".Values.backup.backend.s3" . | nindent 6 }}
     {{- if .Values.backup.scheduler.enabled -}}
    sheduler:
     {{- include ".Values.scheduler" . | nindent 6 }}
    {{- end }}
   
{{- end }}


``